# Generated by Django 4.0 on 2022-01-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('location', models.CharField(max_length=20)),
                ('from_date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_date', models.TimeField()),
                ('to_time', models.TimeField()),
                ('last_date', models.TimeField()),
                ('last_time', models.TimeField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
