# Generated by Django 4.0 on 2022-01-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='last_date',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='last_time',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='to_date',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='to_time',
        ),
    ]
