# Generated by Django 4.0 on 2022-01-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_registration_from_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='from_time',
            field=models.TimeField(null=True),
        ),
    ]
