# Generated by Django 4.0 on 2022-01-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_registration_from_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='last_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='last_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='to_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='to_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='from_date',
            field=models.DateField(null=True),
        ),
    ]
