# Generated by Django 4.0 on 2022-01-06 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_registration_last_date_registration_last_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='Event_Registration',
        ),
    ]
