# Generated by Django 4.0 on 2022-01-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_registration_event_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('select_event', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20)),
                ('num', models.CharField(max_length=30)),
            ],
        ),
    ]
