# Generated by Django 4.0 on 2022-01-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_participant_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_registration',
            name='event_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
