# Generated by Django 4.0 on 2022-01-09 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_event_registration_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_registration',
            name='event_id',
        ),
    ]
