# Generated by Django 4.0 on 2022-01-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_event_registration_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_registration',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
